Kjblog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from blog import views
import os
from django.conf import settings

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^index', views.index),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    #url(r'^admin/login/', views.login),
    #等于下面
    url(r'^admin/login/', views.Login.as_view()),
    url(r'^admin/main/$', views.admin),
    #url(r'^templates/admin/add$', views.add),
    url(r'^admin/love$', views.love),
    url(r'^admin/recycle$', views.recycle),
    #url(r'^templates/admin/', include('blog.urls')),
    url(r'^admin/add$', views.addlist),
    url(r'^admin/category$', views.category),
    url(r'^dela$', views.dela),
    url(r'^index/index_page', views.index_page),
    #url(r'^admin/', include('blog.urls')),
    url(r'^category', views.index_category),
    url(r'^tags', views.index_tags),
]

blog/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
import os
from django.conf import settings

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.index_category, name='category'),
    url(r'^uploadfile$', views.upload, name='upload'),
    url(r'^admin/list$', views.list),
    url(r'^logout/', views.logout),
]

media_root = os.path.join(settings.BASE_DIR, 'upload')
urlpatterns += static('/upload/', document_root=media_root)

comments/urls.py
from django.conf.urls import url
from . import views
app_name = 'comments'
urlpatterns = [
    url(r'^commnet/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# Create your models here.

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField('评论者名字', max_length=100)
    email = models.EmailField('评论者邮箱', max_length=255)
    url = models.URLField('评论者链接', blank=True)
    text = models.TextField('评论内容')
    create_date = models.DateTimeField('评论发表时间', auto_now_add=True)
    article = models.ForeignKey('blog.Article', verbose_name='评论所属文章', on_delete=models.CASCADE)

    def __str__(self):
        return self.body[:20]

templates/index/index_category.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- IE最高引擎 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/lib/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/lib/css/font-awesome.min.css' %}">

    <!-- CSS App -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/themes/flat-blue.css' %}">
</head>
<body>
<div class="app-container">
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="page-title">
                <span class="title">分类</span>
                <div class="description">category</div>
            </div>
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <div class="title">category</div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% get_categories as category_list %}
                        <ul>
                            {% for category in category_list %}
                            <li>
                              <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                            </li>
                            {% empty %}
                            暂无分类！
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="card-header">
                        <div class="card-title">
                            <div class="title">归档</div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% get_date as date_list %}
                        <ul>
                            {% for date in date_list %}
                            <li>
                              <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                            </li>
                            {% empty %}
                            暂无归档！
                            {% endfor %}
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/index/index_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <!-- IE最高引擎 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/lib/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/lib/css/font-awesome.min.css' %}">

    <!-- CSS App -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/custom.css' %}">
    
</head>
<body class="flat-blue">
<div class="app-container">
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <div class="title" >{{ index_list.blog_title }}</div>
                        </div>
                    </div>
                    <div class="card-body">
                        <article class="post i-{{ i.pk }}">
                        <h1 class="entry-title">
                            <a href="">{{ index_list.blog_title }}</a>
                        </h1>
                        </article>
                        
                        <article class="post post-{{ i.pk }}">
                            <header class="entry-header">
                                <div class="entry-meta">
                                    <span >
                                        <a href="#">{{ index_list.blog_category.name }}</a></span>
                                    <span class="post-date"><a href="#"><time class="entry-date"
                                                                              datetime="{{ index_list.created_date }}">{{ index_list.create_date | date:"Y年m月d日 H:i" }}</time></a></span>
                                    <span class="post-author"><a href="#">{{ index_list.blog_author.username }}</a></span>
                                    <span class="comments-link">
                                        <a href="{{ post.get_absolute_url }}#comment-area">{{ i.comment_set.count }} 评论</a></span>
                                    <span class="views-count"><a href="#">{{ i.views }} 阅读</a></span>
                                </div>
                            </header>

                            {% block toc %}
                                <div class="widget widget-content">
                                    <h3 class="widget-title">文章目录</h3>
                                    {{ post.toc|safe }}
                                </div>
                            {% endblock toc %}

                            <div class="entry-content clearfix">
                                {{ index_list.blog_body | safe }}
                                <div class="widget-tag-cloud">
                                    <ul>
                                        标签：
                                        {% for tag in post.tags.all %}
                                            <li><a href="{% url 'blog:tag' tag.pk %}"># {{ tag.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </article>
                        <section class="comment-area" id="comment-area">
                            <hr>
                            <h3>发表评论</h3>
                            <form action="{% url 'comments:post_comment' index_list.pk %}" method="post" class="comment-form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-4">
                                      <label for="{{ form.name.id_for_label }}">名字：</label>
                                      {{ form.name }}
                                      {{ form.name.errors }}
                                    </div>
                                    <div class="col-md-4">
                                      <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                      {{ form.email }}
                                      {{ form.email.errors }}
                                    </div>
                                    <div class="col-md-4">
                                      <label for="{{ form.url.id_for_label }}">URL：</label>
                                      {{ form.url }}
                                      {{ form.url.errors }}
                                    </div>
                                    <div class="col-md-12">
                                      <label for="{{ form.text.id_for_label }}">评论：</label>
                                      {{ form.text }}
                                      {{ form.text.errors }}
                                      <button type="submit" class="comment-btn">发表</button>
                                    </div>
                                  </div>    <!-- row -->
                            </form>
                            <div class="comment-list-panel">
                                <h3>评论列表，共 <span>{{ post.comments.count }}</span> 条评论</h3>
                                <ul class="comment-list list-unstyled">
                                        {% for comment in comment_list %}
                                        <li class="comment-item">
                                            <span class="nickname">{{ comment.name }}</span>
                                            <time class="submit-date"
                                                  datetime="{{ comment.create_date }}">{{ comment.create_date }}</time>
                                            <div class="text">
                                                {{ comment.text }}
                                            </div>
                                        </li>
                                        {% empty %}
                                        暂无评论
                                        {% endfor %}
                                </ul>
                            </div>
                        </section>
                    </div>
            </div>
        </div>
    </div>
</div>
<footer class="app-footer">
    <div class="wrapper">
        <span class="pull-right">2.1 <a href="#"><i class="fa fa-long-arrow-up"></i></a></span> © Powered By Jarbo  2016-2017 - 备案号：<a href="http://www.miitbeian.gov.cn/" title="备案号" target="_blank">黔ICP备17001735号</a>
    </div>
</footer>
</body>
</html>

templates/index/index_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <!-- IE最高引擎 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/lib/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/lib/css/font-awesome.min.css' %}">
    
    <!-- CSS App -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/themes/flat-blue.css' %}">
</head>
<body class="flat-blue">
<div class="app-container">
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <a href="#">
                        <div class="card red summary-inline">
                            <div class="card-body">
                                <i class="icon fa fa-inbox fa-4x"></i>
                                <div class="content">
                                    <div class="title">50</div>
                                    <div class="sub-title">文章</div>
                                </div>
                                <div class="clear-both"></div>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <a href="#">
                        <div class="card yellow summary-inline">
                            <div class="card-body">
                                <i class="icon fa fa-comments fa-4x"></i>
                                <div class="content">
                                    <div class="title">23</div>
                                    <div class="sub-title">留言板</div>
                                </div>
                                <div class="clear-both"></div>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <a href="/tags">
                        <div class="card green summary-inline">
                            <div class="card-body">
                                <i class="icon fa fa-tags fa-4x"></i>
                                <div class="content">
                                    <div class="title">280</div>
                                    <div class="sub-title">标签Tags</div>
                                </div>
                                <div class="clear-both"></div>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <a href="/category">
                        <div class="card blue summary-inline">
                            <div class="card-body">
                                <i class="icon fa fa-life-bouy fa-4x"></i>
                                <div class="content">
                                    <div class="title">16</div>
                                    <div class="sub-title">分类</div>
                                </div>
                                <div class="clear-both"></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>

            <div class="page-title">
                <span class="title">index</span>
                <div class="description">展示页面</div>
            </div>

            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <div class="title">index</div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% for i in abcde %}
                        <article class="post i-{{ i.pk }}">
                        <h1 class="entry-title">
                            <a href="/list/{{ i.pk }}/">{{ i.blog_title }}</a>
                        </h1>
                        </article>

                        <article class="post i-{{ i.pk }}">
                            <div class="entry-meta">
                              <span class="post-category"><a href="#">{{ i.blog_category.name }}</a></span>
                              <span class="post-date"><a href="#"><time class="entry-date"
                                                                        datetime="{{ i.create_date }}">{{ i.create_date | date:"Y年m月d日 H:i:s" }}</time></a></span>
                              <span class="post-author"><a href="#">{{ i.blog_author }}</a></span>
                              <span class="comments-link"><a href="#">4 评论</a></span>
                              <span class="views-count"><a href="#">588 阅读</a></span>
                            </div>
                        </article>

                        <article class="post i-{{ i.pk }}">
                            <div class="entry-content clearfix">
                              <p>{{ i.blog_about }}</p>
                              <div class="read-more cl-effect-14">
                                <a href="/list/{{ i.pk }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                              </div>
                            </div>
                        </article>
                        {% empty %}
                                <div class="no-post">暂时还没有发布的文章！</div>
                        {% endfor %}
                    </div>
            </div>
    </div>
</div>

<footer class="app-footer">
    <div class="wrapper">
        <span class="pull-right">2.1 <a href="#"><i class="fa fa-long-arrow-up"></i></a></span> © Powered By Jarbo  2016-2017 - 备案号：<a href="http://www.miitbeian.gov.cn/" title="备案号" target="_blank">黔ICP备17001735号</a>
    </div>
</footer>
</body>
</html>

templates/index/index_tags.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- IE最高引擎 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/lib/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/lib/css/font-awesome.min.css' %}">

    <!-- CSS App -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/themes/flat-blue.css' %}">
</head>
<body>
<div class="app-container">
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="page-title">
                <span class="title">标签Tags</span>
                <div class="description">Tags</div>
            </div>
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <div class="title">Tags</div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% get_tags as tags_list %}
                        <ul>
                            {% for tags in tags_list %}
                            <li>
                              <a href="#">{{ tags.name }} <span class="post-count">(13)</span></a>
                            </li>
                            {% empty %}
                            暂无标签！
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="card-header">
                        <div class="card-title">
                            <div class="title">归档</div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% get_date as date_list %}
                        <ul>
                            {% for date in date_list %}
                            <li>
                              <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                            </li>
                            {% empty %}
                            暂无归档！
                            {% endfor %}
                        </ul>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
</body>
</html>